apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: ndo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009  # You can specify a node port, or let Kubernetes assign one
  type: NodePort
